# Generated by Django 5.0.6 on 2024-06-12 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('cover_image', models.ImageField(upload_to='products/', verbose_name='cover_image')),
                ('small_description', models.CharField(max_length=255, verbose_name='small_description')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='products.category')),
                ('tags', models.ManyToManyField(related_name='recipes', to='products.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
