# Generated by Django 5.0.6 on 2024-06-26 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_producttype_property_propertyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='products.producttype'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='values',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='products.propertyvalue'),
        ),
    ]
