# Generated by Django 5.0.6 on 2024-06-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_recipe_product_type_recipe_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='values',
        ),
        migrations.AddField(
            model_name='recipe',
            name='values',
            field=models.ManyToManyField(related_name='recipes', to='products.propertyvalue'),
        ),
    ]
