# Generated by Django 5.0.6 on 2024-07-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_recipe_values_recipe_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='values',
        ),
    ]
