# Generated by Django 5.0.6 on 2024-07-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_recipereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipereview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.recipereview'),
        ),
    ]
