# Generated by Django 5.0.6 on 2024-07-31 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_recipe_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
    ]
